// src/components/AddReaction.vue
<script setup lang="ts">
const props = defineProps<{
  isSentByMe: boolean;
  userReactions?: { user: User; value: string }[];
  chatId: string;
  messageId: string;
}>();
import { addReactionToMessage } from "@/lib/apiActions";
import { mapReactions, reactions } from "@/lib/constants";
import { useToast } from "vue-toast-notification";
import { prepareReactions } from "../lib/messageUtils";

const toast = useToast();
const addReaction = async (reaction: string) => {
  const { error } = await addReactionToMessage({
    reaction,
    messageId: props.messageId,
    chatId: props.chatId,
  });

  if (error) toast.error(error);
};
</script>

<template>
  <div
    class="absolute -bottom-7 py-1 px-2 rounded-lg text-base"
    :class="{
      'right-0': isSentByMe,
      'left-0': !isSentByMe,
    }"
  >
    <!-- add reactions -->
    <div class="hidden group-hover:flex group-focus:flex space-x-1">
      <button
        v-for="reaction of reactions"
        :key="reaction[0]"
        @click="addReaction(reaction[0])"
        class="transition hover:scale-125 active:scale-[2] ease-in"
      >
        {{ reaction[1] }}
      </button>
    </div>

    <!-- added reactions -->
    <div
      v-if="userReactions"
      class="group-hover:hidden group-focus:hidden flex space-x-1"
    >
      <span
        v-for="reaction of prepareReactions(userReactions)"
        :key="reaction[0]"
        class="flex space-x-0.5 items-center"
      >
        <span>
          {{ mapReactions[reaction[0]] }}
        </span>
        <span
          class="text-xs font-semibold text-neutral-700 dark:text-neutral-400"
          >{{ reaction[1] }}</span
        >
      </span>
    </div>
  </div>
</template>

// src/components/chat/add-reaction.tsx
import { useAddReaction } from '@/hooks/mutations/useAddReaction';
import { emojis, reactions } from '@/lib/constants';
import { FaceSmileIcon } from '@heroicons/react/24/outline';
import { Dispatch, SetStateAction } from 'react';
import { Popover, PopoverContent, PopoverTrigger } from '../ui/popover';

type Props = {
  message: Message;
  isHovering: boolean;
  setIsPopoverOpen: Dispatch<SetStateAction<boolean>>;
  profile: User | null | undefined;
};
export default function AddReaction({
  message,
  isHovering,
  setIsPopoverOpen,
  profile
}: Props) {
  const { mutate } = useAddReaction({
    chatId: message.chatId,
    messageId: message.id
  });
  const addOrRemoveReaction = (reaction: Reaction) => {
    mutate(reaction);
  };
  const myReaction = message.reactions.find(
    (reaction) => reaction?.userId === profile?.id
  );

  return (
    <Popover onOpenChange={(isOpen) => setIsPopoverOpen(isOpen)}>
      <PopoverTrigger id={`reaction-button-${message.id}`} asChild>
        <button>
          <FaceSmileIcon className="h-5 w-5 dark:text-gray-200" />
        </button>
      </PopoverTrigger>

      <PopoverContent
        className={`h-fit w-fit space-x-2 rounded-full p-2 text-lg ${isHovering ? 'block' : 'lg:hidden'}`}
      >
        {reactions.map((reaction) => (
          <button
            onClick={() => addOrRemoveReaction(reaction)}
            key={reaction}
            className={`transition ease-in hover:scale-125 active:scale-90
             ${myReaction?.reaction === reaction ? 'hidden' : ''}`}
          >
            {emojis[reaction]}
          </button>
        ))}
        {myReaction?.reaction && (
          <button
            onClick={() => addOrRemoveReaction(null)}
            className="inline-flex items-center"
          >
            <span className="mr-0.5 text-sm text-gray-800 dark:text-gray-100">
              Remove
            </span>
            {emojis[myReaction.reaction]}
          </button>
        )}
      </PopoverContent>
    </Popover>
  );
}
