// src/components/SendMessage.vue
<script setup lang="ts">
const props = defineProps<{ chatId: string }>();
import { imageToDataUri } from "@/lib/imageToDataUri";
import { ref } from "vue";
// @ts-ignore
import ImageIcon from "vue-material-design-icons/ImageOutline.vue";
// @ts-ignore
import SendIcon from "vue-material-design-icons/Send.vue";
// @ts-ignore
import CloseIcon from "vue-material-design-icons/Close.vue";
import { useToast } from "vue-toast-notification";
import { scrollToBottom } from "../lib/scrollToBottom";
import { sendMessage } from "@/lib/apiActions";

const toast = useToast();
const image = ref<string>("");
const input = ref<string>("");
const isMessageSending = ref<boolean>(false);

const handleImageChange = async (e: Event) => {
  const imagePickerElement = e.target as HTMLInputElement;
  if (!imagePickerElement.files) return;

  const imageFile = imagePickerElement.files[0];
  image.value = await imageToDataUri(imageFile);
};

const unpickImage = () => {
  image.value = "";
};

const handleMessageSubmit = async (e: Event) => {
  if (isMessageSending.value) return;
  e.preventDefault();
  isMessageSending.value = true;

  if (input.value || image.value) {
    const { error } = await sendMessage({
      chatId: props.chatId,
      text: input.value,
      image: image.value,
    });
    if (error) {
      toast.error(error);
    } else {
      input.value = "";
      image.value = "";
    }
    scrollToBottom();
  }

  isMessageSending.value = false;
};
</script>

<template>
  <div class="fixed bottom-0 left-0 w-full flex z-20 sm:px-3">
    <div class="w-0 mdp:w-full mdp:max-w-[40%] lg:max-w-md"></div>
    <div class="w-full bg-white/80 filter backdrop-blur-3xl sm:pl-2 lg:pl-0 py-3 ">
      <form
        @submit="handleMessageSubmit"
        v-auto-animate
        action=""
        class="w-full bg-neutral-200/30 pl-3 rounded-lg relative flex-grow"
        :class="{ 'pt-1': !!image }"
      >
        <div v-if="image" class="rounded-md py-3 relative w-fit">
          <img loading="lazy" :src="image" alt="" class="h-16 max-w-[120px]" />
          <div
            @click="unpickImage"
            class="absolute cursor-pointer top-1 right-0 bg-white rounded-full"
          >
            <CloseIcon :size="14" />
          </div>
        </div>

        <div class="w-full flex items-center">
          <label for="image" class="text-sky-500">
            <ImageIcon />
          </label>
          <input
            @change="handleImageChange"
            type="file"
            name="image"
            accept="image/*"
            id="image"
            class="hidden"
          />

          <input
            v-model="input"
            type="text"
            placeholder="Type Message"
            class="w-full bg-transparent p-2.5"
          />
          <button
            v-if="!isMessageSending"
            :disabled="!input && !image.valueOf()"
            type="submit"
            class="py-1 px-3 rounded-md text-sky-500 disabled:opacity-50"
          >
            <SendIcon />
          </button>
          <span v-else class="isMessageLoading p-2 mx-3"> </span>
        </div>
      </form>
    </div>
  </div>
</template>

<style>
.isMessageLoading {
  border: 2px solid rgb(59 130 246);
  border-bottom-color: transparent;
  border-radius: 50%;
  display: inline-block;
  box-sizing: border-box;
  animation: messageLoading 1s linear infinite;
}

@keyframes messageLoading {
  0% {
    transform: rotate(0deg);
  }
  100% {
    transform: rotate(360deg);
  }
}
</style>

// src/components/chat/send-message.tsx
import { useSendMessage } from '@/hooks/mutations/useSendMessage';
import { imageToDataUri } from '@/lib/image-service';
import { scrollToBottom } from '@/lib/utils';
import { XMarkIcon } from '@heroicons/react/24/outline';
import { PaperAirplaneIcon, PhotoIcon } from '@heroicons/react/24/solid';
import React, { useState } from 'react';
import { toast } from 'sonner';

type Props = { chatId: string };
export default function SendMessage({ chatId }: Props) {
  const [text, setText] = useState('');
  const [imageDataUri, setImageDataUri] = useState<string | null>(null);
  const [imageFile, setImageFile] = useState<File | null>(null);
  const { mutate } = useSendMessage(chatId);

  const onImagePicked = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const imageFile = e.target.files && e.target.files[0];
    e.target.value = '';
    setImageFile(imageFile);
    if (!imageFile) {
      setImageDataUri(null);
      return;
    }
    const imageDataUri = await imageToDataUri(imageFile);
    setImageDataUri(imageDataUri);
  };

  const unpickImage = () => {
    setImageDataUri('');
    setImageFile(null);
  };

  const sendMessage = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    if (!text && !imageFile) {
      return;
    }
    const textToSend = text;
    const imageToSend = imageFile;
    setText('');
    setImageDataUri('');
    setImageFile(null);

    scrollToBottom();
    const tempId = Math.random().toString();
    mutate(
      {
        image: undefined,
        text: textToSend || undefined,
        id: tempId,
        imageFile: imageToSend
      },
      {
        onError(err) {
          toast.dismiss();
          toast.error(`Could not send message! ${err.message}`);
        }
      }
    );
    scrollToBottom();
  };

  return (
    <section className="sticky bottom-0 left-0 bg-white/90 backdrop-blur-3xl dark:bg-gray-900/50">
      <form
        onSubmit={sendMessage}
        className="relative flex h-16 items-center space-x-3 border-t-2 border-neutral-200/50 px-4 py-2 dark:border-neutral-700/50 md:h-20"
      >
        <input
          type="file"
          id="image-input"
          accept="image/*"
          className="hidden"
          onChange={onImagePicked}
        />
        {imageDataUri && (
          <button
            onClick={unpickImage}
            className="absolute bottom-full mb-2 transition hover:scale-90 hover:brightness-75"
          >
            <div className="relative h-fit w-fit">
              <XMarkIcon className="absolute bottom-full left-full z-50 -m-6 h-6 w-6 bg-black/50 text-gray-400" />
              <img
                src={imageDataUri}
                alt="picked image"
                className="h-40 rounded-sm object-contain"
              />
            </div>
          </button>
        )}
        <label htmlFor="image-input">
          <PhotoIcon className="h-6 w-6 text-rose-500" />
        </label>
        <input
          type="text"
          placeholder="Write a text..."
          value={text}
          onChange={(e) => setText(e.target.value)}
          className="h-10 w-full rounded-full bg-neutral-100 px-5 disabled:opacity-50 dark:bg-gray-700/30"
        />
        <button
          disabled={!text && !imageDataUri}
          type="submit"
          className="space-x-2 rounded-full bg-rose-500 p-2  text-white disabled:opacity-50"
        >
          <PaperAirplaneIcon className="h-5 w-5 text-white" />
        </button>
      </form>
    </section>
  );
}
